### ISSUE TITLE
Hello I just found this! it is nearly working, but not quite.

### ISSUE THREAD

**Issue by Jieiku** [Chaosmeister/PITM#1]
If I have an image on my clipboard, and I paste it into a text area. it successfully attaches the image and adds some code to the post

but the result is this:

![image](https://user-images.githubusercontent.com/106644/144412560-9ee794c5-3c9f-47bd-b9cb-cabd4c760e56.png)

I have manually right click the broken image and copy image link, when I paste the link directly into a browser:

![2021-12-02_03-22](https://user-images.githubusercontent.com/106644/144413005-4c27f776-400d-44c6-8e45-20a125101b3b.png)

What should I do next to debug the problem?

**Comment by Chaosmeister** [comment]
hey hey!
there is one change needed in kanboard base to allow the image to be displayed in the comments

see [here](https://github.com/kanboard/kanboard/pull/4910)

**Comment by Jieiku** [comment]
Awesome! thank you! and thanks a million for this plugin!

**Comment by Jieiku** [comment]
Works Great!

![image](https://user-images.githubusercontent.com/106644/144414595-b7f54b7e-66d6-4ee1-9a6f-757663edfe59.png)
