### ISSUE TITLE
Paste image at cursor position

### ISSUE THREAD

**Issue by rvettori** [Chaosmeister/PITM#11]
When pasting an image, the generated tag is included at the end of the text.
I modified it so that the tag is included at the cursor position.
It worked for me. If it's useful for the project, here's the suggestion.

![image](https://user-images.githubusercontent.com/4119333/179015815-6e6dca27-b371-4cf7-9efe-697cb4d8a25a.png)

**Comment by Chaosmeister** [comment]
Very cool. Thank you!
I'll integrate it on the next occasion

**Comment by RainerBielefeld** [comment]
Yup, that improvement would be the cherry on the cake.

**Comment by Chaosmeister** [comment]
I updated the release
deinstalling and reinstalling should activate the new behaviour
