### ISSUE TITLE
Image url is not functional in description

### ISSUE THREAD

**Issue by Flex301** [Chaosmeister/PITM#16]
In the description the url is `?controller=FileViewerController&action=image&task_id=57&file_id=2`.
However in the attachment section it's `/?controller=FileViewerController&action=thumbnail&file_id=2&project_id=6&task_id=57`.
It looks like there is a missing `project_id` and `/` at the beginning.

<img width="369" alt="image" src="https://user-images.githubusercontent.com/1089145/221490983-2d776715-9bc3-4103-a3fd-36ac92993c30.png">

**Comment by Chaosmeister** [comment]
heyo,  what version of kanboard are you on?

most ids are independent from the projectid, so I put some effort into removing the projectid from most of the links in kanboard itself

**Comment by Flex301** [comment]
I'm on v1.2.20

**Comment by Chaosmeister** [comment]
are you able to update your instance to the latest version? this should resolve the problem

**Comment by Flex301** [comment]
Thank you, I'll try.

**Comment by Flex301** [comment]
Yes, it worked.
