### ISSUE TITLE
Chaosmeister do you use Bigboard plugin?

### ISSUE THREAD

**Issue by Jieiku** [Chaosmeister/PITM#2]
Sorry for posting this here, just was not sure how else to message you.

Do you use the Bigboard plugin? https://github.com/BlueTeck/kanboard_plugin_bigboard

If you do, I opened a few feature request issue reports over there.... if you find any of those features useful enough for you or your team and implement them then please let me know :)

Thanks again for your Kanboard plugins, I have installed them all, they are all very useful additions!

**Comment by Chaosmeister** [comment]
hey no problem!

We currently don't use Bigboard, but I might look into it in the near future, I'll let you know here
