### ISSUE TITLE
PITM won't work on  docker version of Kanboard

### ISSUE THREAD

**Issue by neotaburiss** [Chaosmeister/PITM#5]
I installed PITM together with markdown plus as your instruction with kanboard docker:nightly build(newer than 1.2.1 with your code merged)

But when I  try to paste image into comments/description, it just display as 
![image](https://user-images.githubusercontent.com/78628322/146864239-caa4e582-71e8-4c51-83ac-b329cf8f4f14.png)

Here is PHP log:
PHP message: [info] tasks/pitm/temp/O0QOqS9piC/f7599833314b71480c9137a51d713215"
2021/12/21 11:00:10 [error] 15#15: *240 FastCGI sent in stderr: "PHP message: [info] tasks/pitm/temp/O0QOqS9piC/f7599833314b71480c9137a51d713215" while reading response header from upstream, client: 192.168.1.45, server: localhost, request: "POST /board/16?controller=PasteController&action=upload&plugin=PITM HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "192.168.1.149:9095"

I do looked into Directory **/tasks/pitm/temp/** and found the file are created(should be base64 encoded?)

Could you help check which caused this problem?

Environment:
Application version: master.ee18479b
PHP version: 7.4.27
PHP SAPI: fpm-fcgi
HTTP client cURL
System: Linux 4.19.94-Unraid
Database driver: mysql
Database version: 10.4.15-MariaDB-1:10.4.15+maria~bionic-log
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

Plugin installed:
EnableAttachmentRenaming
Attach Documents for Project Viewers	
Calendar
Coverimage	
Gantt	
Group_assign
KanboardSearchPlugin
metaMagik
Resizable codeblocks
Self-Registration
SubtaskDueDate
Task2pdf
TaskProgressBar
MarkdownPlus
PasteImageToMarkdown
KanboardEssentials

**Comment by Chaosmeister** [comment]
hey, thanks for the report

the images are only shown after pressing `save`

the temp directory is also only used for the moment where the task is created.
After saving, the images are transferred to the task and the link should be converted to the correct file link

I'm not sure why that's not the case for you.

**Comment by neotaburiss** [comment]
Thanks for your reply, I saved and then the error show in docker log.

I tried to debug using syslog as below, but everything seems OK
![image](https://user-images.githubusercontent.com/78628322/146922269-39aae05b-9b54-45bb-95a9-21c120e6882f.png)

I just checked main reason is that PITM can not upload temp images to screenshot, when I paste and save, it just won't apper in image column.

Could you help advice which caused this error?

**Comment by Chaosmeister** [comment]
everything is fine, according to the log

the file got uploaded to the server correctly and now is waiting for the task to be saved.

where do you try to upload the image?

**Comment by neotaburiss** [comment]
When I paste image into comments, data/files/pitm/temp/XXXXXXXX(temp files( are generated.
**(those files are BASE64 encoded, is it intend?)**

I assume those pasted image should be uploaded from data/files/pitm/temp to /data/files/tasks# ,but at tasks# I did not find the file nor the temp file are removed afte I paste.

This is the error log, appear in docker log which seems a dead end for me.....

2021/12/21 19:48:21 [error] 14#14: *1 FastCGI sent in stderr: 
"PHP message: [info] tasks/pitm/temp/0GaCiu2Wb2/799a6ed40b4215cc047d5e1d5db579f2" while reading response header from upstream, client: 192.168.1.45, server: localhost, request: "POST /project/16/task/94?controller=PasteController&action=upload&plugin=PITM HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "192.168.1.149:9095"

**Comment by Chaosmeister** [comment]
> those files are BASE64 encoded
the image is base64 encoded by your browser, then gets uploaded per post request.

looks like FastCGI has an issue with the information, that kanboard logs. it interprets the logmessage as an error?

**Comment by neotaburiss** [comment]
Yes.
![image](https://user-images.githubusercontent.com/78628322/146926535-8e34eb1b-bb13-4714-9d3e-e03fc83c685b.png)

**Comment by Chaosmeister** [comment]
but why?

**Comment by Chaosmeister** [comment]
I don't think this is an error. the plugin just logs the filepath and fastcgi interprets the information as an error.  
you can either send the rest of the log or try to find other errors in it.

**Comment by neotaburiss** [comment]
Hello Chaosmeister , first I wish you a Merry Christmas and a Happy New Year!

After trying back and forth, I found where is the problem:

At my kanboard, there will be two task links(I do not know it is intend or some plugin change it), for example task#94

1. http://192.168.1.149:9095/?controller=TaskViewController&action=show&task_id=94
2. http://192.168.1.149:9095/project/16/task/94

PTIM and CCIT works perfect on no.1 link but will not load on no.2 link,

Could you help check if it it is URL problem?

**Comment by Chaosmeister** [comment]
hey sorry for the late response

it looks like you configured [URL rewriting](https://docs.kanboard.org/en/latest/admin_guide/url_rewriting.html) on link 2

I'll take a look if I can make PITM work with it
