### ISSUE TITLE
PITM can not work when enable url rewrite in config.php

### ISSUE THREAD

**Issue by greyaz** [Chaosmeister/PITM#8]
As PITM is based on url parameters, when url rewrite enabled, PITM can not get the task id.

**Comment by Chaosmeister** [comment]
hey, 
yeah it's the same problem with the docker version in #5 
I'm not using the url-rewrite feature, I'll need to figure out a way to implement and debug this

**Comment by greyaz** [comment]
I opened a new pull request to solve it.  Please have a look.

**Comment by Chaosmeister** [comment]
will do
thank you very much!

**Comment by greyaz** [comment]
You are welcome

**Comment by Chaosmeister** [comment]
I merged it, created a new release and a [merge request](https://github.com/kanboard/website/pull/307) for the plugin installer 👍
